Update clspv reflection non-semantic instruction set
KhronosGroup/SPIRV-Registry pull request #178
Opened 2022-12-08 17:24 UTC by callumfare

Add support to the clspv reflection non-semantic instruction set for:
* Printf builtin
* Device address push constants for module-scope constants and program-scope global variables

This contribution is being made by Codeplay on behalf of Samsung.

2022-12-14 21:03 UTC, alan-baker requested changes

2022-12-16 15:42 UTC, callumfare commented
@alan-baker Thanks for the review, I've addressed your comments including adding the `NumArguments` operand. I also corrected the description of the printf buffer - it doesn't need to be zero-initialized, only the first 4 bytes need to be zeroed.

2022-12-22 11:24 UTC, callumfare commented
I've addressed the review feedback. I've also added a change from @FMarno which adds another operand to support clGetKernelInfo with `CL_KERNEL_ATTRIBUTES`

2023-01-03 14:46 UTC, alan-baker approved these changes

2023-01-03 14:46 UTC, merged