Update Execution Mode argument name to march SYCL extension
KhronosGroup/SPIRV-Registry pull request #188
Opened 2023-02-28 18:52 UTC by tiwaria1

The argument name for the mode "RegisterMapInterfaceINTEL" in the SPIRV spec does not match the name in the [SYCL extension (https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_intel_fpga_kernel_interface_properties.asciidoc) . This PR updates the SPIRV extension to align the names.

2023-02-28 18:54 UTC, tiwaria1 commented
@MrSidims  Could you review this minor change (I'll update the translator PR too)

2023-03-01 15:35 UTC, bashbaug commented
If we do this I think we'll want to update the grammar file and headers also (https://github.com/KhronosGroup/SPIRV-Headers/pull/317).

2023-03-01 15:36 UTC, bashbaug requested changes
If we do this please build an HTML spec with these changes as well.

2023-03-01 15:48 UTC, tiwaria1 commented
@bashbaug I updated the html spec and the grammar file on the headers PR. Thank you for reviewing so quickly.

2023-03-01 16:28 UTC, bashbaug approved these changes
Thanks, LGTM!

2023-03-01 16:43 UTC, merged