Update clspv reflection non-semantic instruction set
KhronosGroup/SPIRV-Registry pull request #220
Opened 2023-10-11 15:07 UTC by rjodinchr

Add support for sampler mask push constant

2023-10-11 15:07 UTC, rjodinchr commented
@kpet @alan-baker  could you review this PR please?

2023-10-16 14:35 UTC, alan-baker requested changes
Just nits

2023-10-16 14:35 UTC, alan-baker commented on nonsemantic/NonSemantic.ClspvReflection.asciidoc
> +valid, *clspv* will have generated the code to normalized the coordinates.
```suggestion
sampler. It means that the kernel accesses 3D images with this sampler,
but Vulkan does not allow accessing 3D images with a sampler using unnormalized coordinates. *Clspv* will generates code to normalized the coordinates.
```

2023-10-16 14:35 UTC, alan-baker commented on nonsemantic/NonSemantic.ClspvReflection.asciidoc
> +*clspv* will choose at runtime whether to use the original coordinates or the
```suggestion
*Clspv* will choose at runtime whether to use the original coordinates or the
```

2023-10-16 14:47 UTC, alan-baker approved these changes

2023-10-18 15:42 UTC, bashbaug commented
Merging as discussed in the October 18th teleconference.

2023-10-18 15:42 UTC, merged